---
title: "Breast cancer prescribing"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(magrittr)
library(reactable)

```






```
The following document sets out the observed and expected usage of the breast 
cancer medicines abemaciclib and neratinib. These medicines were selected as 
we have access to both primary and secondary care prescribing data and they are 
largely prescribed for an idendifiable cohort of patients where we can estimate 
expected usage. 

```

# Abemaciclib


```
The observed usage of abemaciclib has increased sinced it was first authorised 
in 2018. In 2021 it was approaching the estimated expected level of prescribing. 

```


```{r}
Abemaciclib_data3 <- read.csv ("C:\\R_Projects\\myrepo\\Abemaciclib3.csv")
annotation <- data.frame(
   x = c(2019,2020.5, 2021),
   y = c(750,750,750),
   label = c("TA563", "TA725", "TA810"))
   h_line <- 4059
ggplot(data=Abemaciclib_data3, aes(x=Year, y=People)) +
    geom_line(stat='identity',color="darkblue", fill="lightblue") +
    geom_hline(yintercept = h_line) +
    geom_text(aes(2020, h_line, label = "Expected usage", vjust = -1)) +
    ylim(0, 5000) +
    xlim(2018,2021)+
    theme_minimal() +
    labs(title = "Abemaciclib primary and secondary care prescribing, England, 2018-2021") +
    geom_text(data=annotation, aes( x=x, y=y, label=label),                 , 
           color="orange", 
           size=4 , angle=0, fontface="bold" )





```

## Eligible population 

```
Around 4,000 people are expected to recieve treatment with abemaciclib in England annually.
This has been taken from the Resource impact template developed for the NICE technology appraisal 'Abemaciclib with endocrine therapy for adjuvant treatment of hormone receptor-positive, HER2-negative, node-positive early breast cancer at high risk of recurrencedor', published July 2022. 
```
```{r}
Abemaciclib_table1<- read.csv("./Abemaciclib_table1.csv")
reactable(Abemaciclib_table1)
```

## Observed usage
```
The table below is taken from data in the April 2022 publication of the innovation scorecard. It shoes secondary care prescribing data by quarter in England for abemaciclib, also includes the very small amount of primary care data observed in the period. 
```

```{r}
Abemaciclib_table2<- read.csv("./Abemaciclib_table2.csv")
reactable(Abemaciclib_table2)
```
## NICE guidance

```{r}
Abemaciclib_table3<- read.csv("./Abemaciclib_table3.csv")
reactable(Abemaciclib_table3)
```
## Therapeutic indications 

### Early Breast Cancer

```
Verzenios in combination with endocrine therapy is indicated for the adjuvant treatment of adult patients with hormone receptor (HR)-positive, human epidermal growth factor receptor 2 (HER2)-negative, node-positive early breast cancer at high risk of recurrence.
In pre- or perimenopausal women, aromatase inhibitor endocrine therapy should be combined with a luteinising hormone-releasing hormone (LHRH) agonist.
```

### Advanced or Metastatic Breast Cancer
```
Verzenios is indicated for the treatment of women with hormone receptor (HR)-positive, human epidermal growth factor receptor 2 (HER2)-negative locally advanced or metastatic breast cancer in combination with an aromatase inhibitor or fulvestrant as initial endocrine-based therapy, or in women who have received prior endocrine therapy.
In pre- or perimenopausal women, the endocrine therapy should be combined with a LHRH agonist.

```

# Neratinib




